### ISSUE TITLE
地震の際に震度をツイートする機能を追加

### ISSUE THREAD

**Issue by dezaiso** [dezaiso/jisakujien#6]
https://github.com/dezaiso/jisakujien/blob/master/Jishin.php
にて作成＆作動中。

[ここ](http://www26.atwiki.jp/easybotter_wiki/pages/39.html) とか [ここ](http://koi-ha-utsukusii.lovepop.jp/hoitan_WP/?p=139) を参考にしつつ、地震の際に止めないで震度をツイートするように改変したつもりなのだが実際にそうなるかは現状未確認。

以下のふたつは正常に動作中。
- goo 天気 地震情報RSSの読み込みと時間取得の `earthquake_pubtime.txt`
- https://github.com/dezaiso/jisakujien/blob/master/bot.php
  による `Jishin_joutai.txt` への値の書き込み

**Comment by dezaiso** [comment]
``` php
//=============================
//地震判定（毎回）
//=============================

$shindo = $ebo->jisin();

if( $shindo['num'] > 0){ //値が返ってきてたら
  $joutai[0] = TRUE; //「地震が起きた」フラグを立てる
}
```

の箇所、いちど「地震が起きたフラグ」が立ったらそのままになってしまうので
ツイート終了後に通常時フラグを立て直す必要がある。

``` php
$joutai[0] = FALSE;//「地震が起きた」フラグを通常時にもどす
```

**Comment by hgw** [comment]
すごい開発速度ですね :dash:

**Comment by dezaiso** [comment]
地震機能はちょっと保留 :tired_face:

**Comment by dezaiso** [comment]
ひとまず #17 まで

今後は
- [ ] `jishin.txt`を読み込みツイートさせる
- [ ] ツイートがダブらないよう処理
- [ ] ツイートしたら `jishin.txt`および `jishin_joutai.txt`を初期化。

**Comment by dezaiso** [comment]
いや、初期化する必要ないか…

**Comment by dezaiso** [comment]
テスト完了とみなして本番化。
プログラム整理して、`Jishin_joutai.txt` を削除

不具合出るまで成功とみなし、閉じます

**Comment by dezaiso** [comment]
通常のランダムツィートをしなくなってしまった。。

**Comment by dezaiso** [comment]
通常にもどりました
